export type Locale = "en" | "es";

export const messages = {
  en: {
    language: "Español", brand: "Church Finance",
    nav: { dashboard: "Dashboard", activity: "Activity", income: "Record income", expense: "Record expense", reports: "Reports", primary: "Primary navigation" },
    account: { signedIn: "Signed in as", signOut: "Sign out", signingOut: "Signing out…" },
    login: { title: "Sign in", lede: "Use your authorized church account to continue.", loading: "Loading sign-in…", email: "Email address", password: "Password", signIn: "Sign in", signingIn: "Signing in…", error: "The email or password is incorrect." },
    dashboard: { title: "Financial overview", lede: "Posted activity across the organization’s financial accounts.", unavailable: "Summary unavailable", balance: "Available balance", income: "Income this month", expenses: "Expenses this month", summary: "Financial summary", activity: "View activity" },
    income: { eyebrow: "Transactions", title: "Record income", lede: "Enter the deposit details below. The server validates and saves the transaction to the church ledger.", amount: "Amount", date: "Transaction date", category: "Category", selectCategory: "Select a category", fund: "Fund or purpose", selectFund: "Select a fund", description: "Description", save: "Save income", saving: "Saving…", saved: "Income saved", reference: "Reference", invalid: "The transaction could not be validated." },
    activity: { eyebrow: "Activity", title: "Income activity", lede: "The latest posted income for your organization.", unavailable: "Activity unavailable", empty: "No income yet", emptyText: "Saved income transactions will appear here.", date: "Date", description: "Description", category: "Category", fund: "Fund", account: "Account", amount: "Amount", ref: "Ref." },
    pages: { accounts: "Accounts", financialAccounts: "Financial accounts", accountsLater: "Checking, savings, and cash accounts will be implemented later.", reports: "Reports", financialReports: "Financial reports", reportsLater: "Reports will be added after transaction persistence is approved.", administration: "Administration", settings: "Settings", settingsLater: "Categories, funds, users, and permissions will be implemented later.", transactions: "Transactions", register: "Transaction register", registerText: "Income and expense entry are available." },
    expense: { eyebrow: "Transactions", title: "Record expense", lede: "Enter the payment details below. The server validates and saves the expense to the church ledger.", amount: "Amount", date: "Transaction date", category: "Category", selectCategory: "Select a category", fund: "Fund or purpose", selectFund: "Select a fund", description: "Description", reference: "Check or card reference (optional)", save: "Save expense", saving: "Saving…", saved: "Expense saved", transactionReference: "Transaction reference", paymentReference: "Payment reference", none: "None", invalid: "The expense could not be validated." },
    categories: ["Building rent", "Utilities", "Bank fees", "Church insurance", "Essential supplies", "Pastor support and travel", "Children's guides", "Magazine and literature", "Presbytery contributions", "Other expense"],
    categoryLabels: ["Building rent", "Utilities", "Bank fees", "Church insurance", "Essential supplies", "Pastor support and travel", "Children’s guides", "Magazine and literature", "Presbytery contributions", "Other expense"],
    funds: ["Support of the work", "General congregation", "Children's commission", "Legal and building", "Presbytery"],
    fundLabels: ["Support of the work", "General congregation", "Children’s commission", "Legal and building", "Presbytery"],
  },
  es: {
    language: "English", brand: "Finanzas de la Iglesia",
    nav: { dashboard: "Resumen", activity: "Actividad", income: "Registrar ingreso", expense: "Registrar gasto", reports: "Reportes", primary: "Navegación principal" },
    account: { signedIn: "Sesión iniciada como", signOut: "Cerrar sesión", signingOut: "Cerrando sesión…" },
    login: { title: "Iniciar sesión", lede: "Use su cuenta autorizada de la iglesia para continuar.", loading: "Cargando inicio de sesión…", email: "Correo electrónico", password: "Contraseña", signIn: "Iniciar sesión", signingIn: "Iniciando sesión…", error: "El correo electrónico o la contraseña son incorrectos." },
    dashboard: { title: "Resumen financiero", lede: "Actividad registrada en las cuentas financieras de la organización.", unavailable: "Resumen no disponible", balance: "Saldo disponible", income: "Ingresos de este mes", expenses: "Gastos de este mes", summary: "Resumen financiero", activity: "Ver actividad" },
    income: { eyebrow: "Transacciones", title: "Registrar ingreso", lede: "Ingrese los datos del depósito. El servidor valida y guarda la transacción en el registro contable de la iglesia.", amount: "Monto", date: "Fecha de la transacción", category: "Categoría", selectCategory: "Seleccione una categoría", fund: "Fondo o propósito", selectFund: "Seleccione un fondo", description: "Descripción", save: "Guardar ingreso", saving: "Guardando…", saved: "Ingreso guardado", reference: "Referencia", invalid: "No se pudo validar la transacción." },
    activity: { eyebrow: "Actividad", title: "Actividad de ingresos", lede: "Los ingresos registrados más recientes de su organización.", unavailable: "Actividad no disponible", empty: "Aún no hay ingresos", emptyText: "Los ingresos guardados aparecerán aquí.", date: "Fecha", description: "Descripción", category: "Categoría", fund: "Fondo", account: "Cuenta", amount: "Monto", ref: "Ref." },
    pages: { accounts: "Cuentas", financialAccounts: "Cuentas financieras", accountsLater: "Las cuentas de cheques, ahorros y efectivo se implementarán más adelante.", reports: "Reportes", financialReports: "Reportes financieros", reportsLater: "Los reportes se agregarán después de aprobar el registro de transacciones.", administration: "Administración", settings: "Configuración", settingsLater: "Las categorías, fondos, usuarios y permisos se implementarán más adelante.", transactions: "Transacciones", register: "Registro de transacciones", registerText: "El registro de ingresos y gastos está disponible." },
    expense: { eyebrow: "Transacciones", title: "Registrar gasto", lede: "Ingrese los datos del pago. El servidor valida y guarda el gasto en el registro contable de la iglesia.", amount: "Monto", date: "Fecha de la transacción", category: "Categoría", selectCategory: "Seleccione una categoría", fund: "Fondo o propósito", selectFund: "Seleccione un fondo", description: "Descripción", reference: "Referencia de cheque o tarjeta (opcional)", save: "Guardar gasto", saving: "Guardando…", saved: "Gasto guardado", transactionReference: "Referencia de transacción", paymentReference: "Referencia de pago", none: "Ninguna", invalid: "No se pudo validar el gasto." },
    categories: ["Building rent", "Utilities", "Bank fees", "Church insurance", "Essential supplies", "Pastor support and travel", "Children's guides", "Magazine and literature", "Presbytery contributions", "Other expense"],
    categoryLabels: ["Renta del edificio", "Servicios públicos", "Cargos bancarios", "Seguro de la iglesia", "Artículos de primera necesidad", "Apoyo al pastor y viajes", "Guías infantiles", "Revistas y literatura", "Aportaciones presbiteriales", "Otro gasto"],
    funds: ["Support of the work", "General congregation", "Children's commission", "Legal and building", "Presbytery"],
    fundLabels: ["Sustento de la obra", "Congregación general", "Comisión infantil", "Legal y edificio", "Presbiterio"],
  },
} as const;
export function getMessages(locale: Locale) { return messages[locale]; }
