export type Locale = "en" | "es";

export const messages = {
  en: {
    language: "Español", brand: "Church Finance",
    nav: { dashboard: "Dashboard", accounts: "Accounts", categories: "Categories", funds: "Funds", budgets: "Budgets", activity: "Activity", transaction: "Record transaction", income: "Record income", expense: "Record expense", reports: "Reports", settings: "Users & permissions", primary: "Primary navigation" },
    account: { signedIn: "Signed in as", signOut: "Sign out", signingOut: "Signing out…" },
    login: { title: "Sign in", lede: "Use your authorized church account to continue.", loading: "Loading sign-in…", email: "Email address", password: "Password", signIn: "Sign in", signingIn: "Signing in…", error: "The email or password is incorrect.", invited: "Have an invitation?", createAccount: "Create your account" },
    signup: { title: "Create your invited account", lede: "Enter the email address your administrator invited. We will send a secure link so you can create your password.", email: "Invited email address", send: "Send account setup link", sending: "Sending…", sent: "Check your email for a secure account setup link.", error: "The setup link could not be sent. Confirm that this is the invited email address.", rateLimited: "Too many setup emails were requested. Wait an hour before trying again, or configure Custom SMTP.", backToLogin: "Back to sign in" },
    callback: { title: "Verifying your invitation", lede: "Please wait while we securely verify your account setup link.", loading: "Verifying link…", invalid: "This link could not be verified. Request a new setup link and open it in this same browser." },
    recovery: { title: "Verify your setup code", lede: "Enter the invited email address and the one-time code from the newest account setup email.", email: "Invited email address", code: "Setup code", verify: "Verify code", verifying: "Verifying…", invalid: "The code is invalid or expired. Request a new setup email and use its newest code." },
    dashboard: { title: "Financial overview", lede: "Posted activity across the organization’s financial accounts.", unavailable: "Summary unavailable", balance: "Available balance", income: "Income this month", expenses: "Expenses this month", summary: "Financial summary", activity: "View activity" },
    transaction: { eyebrow: "Transactions", title: "Record transaction", lede: "Choose whether money was received or paid, then select the matching category and details.", type: "Transaction type", typeHint: "Income increases the balance. Expenses decrease the balance.", income: "Income — money received", expense: "Expense — money paid", account: "Financial account", selectAccount: "Select a financial account", accountHint: "The balance of this account will be updated.", contributions: "Contributions and offerings", earnedIncome: "Rental and earned income", facilities: "Facilities", operations: "Operations", ministry: "Ministry and church support", other: "Other" },
    income: { eyebrow: "Transactions", title: "Record income", lede: "Enter the deposit details below. The server validates and saves the transaction to the church ledger.", amount: "Amount", date: "Transaction date", category: "Income category", categoryHint: "Income categories represent money received and increase the available balance.", selectCategory: "Select an income category", fund: "Fund or purpose", selectFund: "Select a fund", description: "Description", save: "Save income", saving: "Saving…", saved: "Income saved", reference: "Reference", invalid: "The transaction could not be validated." },
    activity: { eyebrow: "Activity", title: "Transaction activity", lede: "The latest posted and voided income and expenses for your organization.", unavailable: "Activity unavailable", empty: "No transactions yet", emptyText: "Saved income and expense transactions will appear here.", date: "Date", type: "Type", incomeType: "Income", expenseType: "Expense", status: "Status", posted: "Posted", voided: "Voided", voidReason: "Reason", voidedOn: "Voided", description: "Description", category: "Category", fund: "Fund", account: "Account", amount: "Amount", ref: "Ref.", paymentRef: "Payment", actions: "Actions", edit: "Edit" },
    editTransaction: { eyebrow: "Transactions", title: "Edit transaction", lede: "Correct the transaction details below. The transaction type and audit identity remain unchanged.", type: "Transaction type", typeLocked: "Income cannot be changed to an expense, or an expense to income.", amount: "Amount", date: "Transaction date", category: "Category", fund: "Fund", account: "Account", description: "Description", reference: "Check or card reference (optional)", save: "Save changes", saving: "Saving…", saved: "Changes saved.", cancel: "Cancel", invalid: "The transaction could not be updated.", voidTitle: "Void transaction", voidText: "This removes the amount from balances and reports while preserving the audit record.", voidAction: "Void transaction", voidReason: "Reason for voiding", confirmVoid: "Confirm void", voiding: "Voiding…", keepTransaction: "Keep transaction", voidInvalid: "The transaction could not be voided." },
    reports: { eyebrow: "Reports", title: "Monthly financial report", lede: "Posted income, expenses, and net results for each month.", unavailable: "Report unavailable", income: "Income", expenses: "Expenses", net: "Net result", month: "Month", year: "Year", viewReport: "View report", total: "Year total", details: "Category details", back: "Back to monthly report", transactions: "transactions", empty: "No posted transactions for this selection.", date: "Date", description: "Description", fund: "Fund", account: "Account", reference: "Payment reference", amount: "Amount", downloadPdf: "Download PDF", detailedDownload: "Detailed PDF report", detailedDownloadText: "Download every matching transaction for the full year or one month.", period: "Period", fullYear: "Full year", transactionType: "Transaction type", allTransactions: "All transactions", downloadDetailedPdf: "Download detailed PDF" },
    settings: { title: "Users & permissions", lede: "View organization members and control what each person can do.", organization: "Organization", members: "Members", member: "Member", role: "Role", joined: "Joined", currentUser: "You", save: "Save role", saving: "Saving…", saved: "Role updated.", administratorOnly: "Only administrators can change member roles.", finalAdministrator: "Add another administrator before changing this role.", inviteTitle: "Invite a new account", inviteText: "Send an email invitation so this person can create a password and join the organization.", invite: "Send invitation", inviting: "Sending…", invited: "Invitation sent and member added.", inviteError: "The invitation could not be completed. Confirm the address is not already registered and that invitations are configured.", setupLink: "Send setup link", sendingSetupLink: "Sending…", setupLinkSent: "Account setup link sent.", setupLinkError: "The setup link could not be sent.", activeStatus: "Active access", inactiveStatus: "Access deactivated", deactivate: "Deactivate access", deactivating: "Deactivating…", deactivateConfirm: "Deactivate this member's access? They will immediately lose access to church financial data, but their audit history will remain.", deactivated: "Member access deactivated.", restore: "Restore access", restoring: "Restoring…", restored: "Member access restored.", accessError: "Member access could not be changed.", addTitle: "Add an existing account", addText: "Use this when the person already has an account in Supabase Authentication.", email: "Account email", addRole: "Initial role", add: "Add member", adding: "Adding…", added: "Member added.", addError: "The member could not be added. Confirm that the account exists and is not already assigned.", unavailable: "Members unavailable", errors: "The role could not be changed.", roleLabels: { administrator: "Administrator", treasurer: "Treasurer", data_entry: "Data entry", approver: "Approver", viewer: "Viewer" } },
    invitation: { title: "Create your password", lede: "Finish setting up your church finance account.", password: "Password", confirmPassword: "Confirm password", save: "Create account", saving: "Creating account…", mismatch: "The passwords do not match.", invalid: "This invitation is invalid or has expired. Ask an administrator for a new invitation.", success: "Account created." },
    accounts: { title: "Financial accounts", lede: "Track checking, savings, cash, and petty-cash balances in one place.", unavailable: "Accounts unavailable", createTitle: "Create financial account", createText: "Add an account and its starting balance. Only administrators can create accounts.", name: "Account name", type: "Account type", openingBalance: "Opening balance", openingBalanceHint: "The balance before transactions recorded in this app.", create: "Create account", creating: "Creating…", created: "Financial account created.", createError: "The financial account could not be created.", administratorOnly: "Only administrators can create financial accounts.", currentBalance: "Current balance", opening: "Opening balance", noAccounts: "No financial accounts have been created.", status: "Status", active: "Active", inactive: "Inactive", manage: "Manage account", saveChanges: "Save changes", savingChanges: "Saving…", updated: "Financial account updated.", updateError: "The financial account could not be updated.", finalActive: "The final active account cannot be deactivated.", typeLabels: { checking: "Checking", savings: "Savings", cash: "Cash", petty_cash: "Petty cash", other: "Other" } },
    categoryManagement: { title: "Category management", lede: "Manage the income and expense categories available when recording transactions.", createTitle: "Create category", createText: "Choose whether the new category is for money received or money paid.", name: "Category name", type: "Category type", income: "Income", expense: "Expense", create: "Create category", creating: "Creating…", created: "Category created.", createError: "The category could not be created.", administratorOnly: "Only administrators can manage categories.", status: "Status", active: "Active", inactive: "Inactive", manage: "Manage category", saveChanges: "Save changes", savingChanges: "Saving…", updated: "Category updated.", updateError: "The category could not be updated.", noCategories: "No categories have been created." },
    fundManagement: { title: "Fund management", lede: "Manage the designated funds available when recording transactions.", createTitle: "Create fund", createText: "Add a purpose or designation for tracking income and expenses.", name: "Fund name", create: "Create fund", creating: "Creating…", created: "Fund created.", createError: "The fund could not be created.", administratorOnly: "Only administrators can manage funds.", status: "Status", active: "Active", inactive: "Inactive", manage: "Manage fund", saveChanges: "Save changes", savingChanges: "Saving…", updated: "Fund updated.", updateError: "The fund could not be updated.", noFunds: "No funds have been created." },
    budgetManagement: { title: "Budget management", lede: "Set monthly spending targets and compare them with posted expenses.", createTitle: "Set monthly budget", createText: "Saving the same category and month updates its existing budget.", category: "Expense category", month: "Budget month", amount: "Budget amount", save: "Save budget", saving: "Saving…", saved: "Budget saved.", error: "The budget could not be saved.", administratorOnly: "Only administrators can manage budgets.", noBudgets: "No budgets have been set for this year.", budgeted: "Budgeted", actual: "Actual spent", remaining: "Remaining", over: "Over budget", viewYear: "View year" },
    pages: { accounts: "Accounts", financialAccounts: "Financial accounts", accountsLater: "Checking, savings, and cash accounts will be implemented later.", reports: "Reports", financialReports: "Financial reports", reportsLater: "Reports will be added after transaction persistence is approved.", administration: "Administration", settings: "Settings", settingsLater: "Categories, funds, users, and permissions will be implemented later.", transactions: "Transactions", register: "Transaction register", registerText: "Income and expense entry are available." },
    expense: { eyebrow: "Transactions", title: "Record expense", lede: "Enter the payment details below. The server validates and saves the expense to the church ledger.", amount: "Amount", date: "Transaction date", category: "Expense category", categoryHint: "Expense categories represent money paid and decrease the available balance.", selectCategory: "Select an expense category", fund: "Fund or purpose", selectFund: "Select a fund", description: "Description", reference: "Check or card reference (optional)", save: "Save expense", saving: "Saving…", saved: "Expense saved", transactionReference: "Transaction reference", paymentReference: "Payment reference", none: "None", invalid: "The expense could not be validated." },
    categories: ["Building rent", "Utilities", "Bank fees", "Church insurance", "Essential supplies", "Pastor support and travel", "Children's guides", "Magazine and literature", "Presbytery contributions", "Other expense"],
    categoryLabels: ["Building rent payment (money paid)", "Utilities", "Bank fees", "Church insurance", "Essential supplies", "Pastor support and travel", "Children’s guides", "Magazine and literature", "Presbytery contributions", "Other expense"],
    funds: ["Support of the work", "General congregation", "Children's commission", "Legal and building", "Presbytery"],
    fundLabels: ["Support of the work", "General congregation", "Children’s commission", "Legal and building", "Presbytery"],
  },
  es: {
    language: "English", brand: "Finanzas de la Iglesia",
    nav: { dashboard: "Resumen", accounts: "Cuentas", categories: "Categorías", funds: "Fondos", budgets: "Presupuestos", activity: "Actividad", transaction: "Registrar transacción", income: "Registrar ingreso", expense: "Registrar gasto", reports: "Reportes", settings: "Usuarios y permisos", primary: "Navegación principal" },
    account: { signedIn: "Sesión iniciada como", signOut: "Cerrar sesión", signingOut: "Cerrando sesión…" },
    login: { title: "Iniciar sesión", lede: "Use su cuenta autorizada de la iglesia para continuar.", loading: "Cargando inicio de sesión…", email: "Correo electrónico", password: "Contraseña", signIn: "Iniciar sesión", signingIn: "Iniciando sesión…", error: "El correo electrónico o la contraseña son incorrectos.", invited: "¿Tiene una invitación?", createAccount: "Cree su cuenta" },
    signup: { title: "Cree su cuenta invitada", lede: "Ingrese el correo que invitó el administrador. Le enviaremos un enlace seguro para crear su contraseña.", email: "Correo electrónico invitado", send: "Enviar enlace de configuración", sending: "Enviando…", sent: "Revise su correo para abrir el enlace seguro de configuración.", error: "No se pudo enviar el enlace. Confirme que este sea el correo electrónico invitado.", rateLimited: "Se solicitaron demasiados correos de configuración. Espere una hora antes de intentarlo de nuevo o configure SMTP personalizado.", backToLogin: "Volver a iniciar sesión" },
    callback: { title: "Verificando su invitación", lede: "Espere mientras verificamos de forma segura el enlace de configuración.", loading: "Verificando enlace…", invalid: "No se pudo verificar este enlace. Solicite uno nuevo y ábralo en este mismo navegador." },
    recovery: { title: "Verifique su código de configuración", lede: "Ingrese el correo invitado y el código de un solo uso del correo de configuración más reciente.", email: "Correo electrónico invitado", code: "Código de configuración", verify: "Verificar código", verifying: "Verificando…", invalid: "El código no es válido o venció. Solicite un correo nuevo y use el código más reciente." },
    dashboard: { title: "Resumen financiero", lede: "Actividad registrada en las cuentas financieras de la organización.", unavailable: "Resumen no disponible", balance: "Saldo disponible", income: "Ingresos de este mes", expenses: "Gastos de este mes", summary: "Resumen financiero", activity: "Ver actividad" },
    transaction: { eyebrow: "Transacciones", title: "Registrar transacción", lede: "Elija si el dinero fue recibido o pagado y después seleccione la categoría y los detalles correspondientes.", type: "Tipo de transacción", typeHint: "Los ingresos aumentan el saldo. Los gastos disminuyen el saldo.", income: "Ingreso — dinero recibido", expense: "Gasto — dinero pagado", account: "Cuenta financiera", selectAccount: "Seleccione una cuenta financiera", accountHint: "El saldo de esta cuenta se actualizará.", contributions: "Aportaciones y ofrendas", earnedIncome: "Rentas e ingresos obtenidos", facilities: "Edificio e instalaciones", operations: "Operaciones", ministry: "Ministerio y apoyo de la iglesia", other: "Otros" },
    income: { eyebrow: "Transacciones", title: "Registrar ingreso", lede: "Ingrese los datos del depósito. El servidor valida y guarda la transacción en el registro contable de la iglesia.", amount: "Monto", date: "Fecha de la transacción", category: "Categoría de ingreso", categoryHint: "Las categorías de ingreso representan dinero recibido y aumentan el saldo disponible.", selectCategory: "Seleccione una categoría de ingreso", fund: "Fondo o propósito", selectFund: "Seleccione un fondo", description: "Descripción", save: "Guardar ingreso", saving: "Guardando…", saved: "Ingreso guardado", reference: "Referencia", invalid: "No se pudo validar la transacción." },
    activity: { eyebrow: "Actividad", title: "Actividad de transacciones", lede: "Los ingresos y gastos registrados y anulados más recientes de su organización.", unavailable: "Actividad no disponible", empty: "Aún no hay transacciones", emptyText: "Los ingresos y gastos guardados aparecerán aquí.", date: "Fecha", type: "Tipo", incomeType: "Ingreso", expenseType: "Gasto", status: "Estado", posted: "Registrada", voided: "Anulada", voidReason: "Motivo", voidedOn: "Anulada", description: "Descripción", category: "Categoría", fund: "Fondo", account: "Cuenta", amount: "Monto", ref: "Ref.", paymentRef: "Pago", actions: "Acciones", edit: "Editar" },
    editTransaction: { eyebrow: "Transacciones", title: "Editar transacción", lede: "Corrija los detalles de la transacción. El tipo y la identidad de auditoría no cambian.", type: "Tipo de transacción", typeLocked: "Un ingreso no se puede cambiar a gasto, ni un gasto a ingreso.", amount: "Monto", date: "Fecha de la transacción", category: "Categoría", fund: "Fondo", account: "Cuenta", description: "Descripción", reference: "Referencia de cheque o tarjeta (opcional)", save: "Guardar cambios", saving: "Guardando…", saved: "Cambios guardados.", cancel: "Cancelar", invalid: "No se pudo actualizar la transacción.", voidTitle: "Anular transacción", voidText: "Esto elimina el monto de los saldos y reportes, pero conserva el registro de auditoría.", voidAction: "Anular transacción", voidReason: "Motivo de la anulación", confirmVoid: "Confirmar anulación", voiding: "Anulando…", keepTransaction: "Conservar transacción", voidInvalid: "No se pudo anular la transacción." },
    reports: { eyebrow: "Reportes", title: "Reporte financiero mensual", lede: "Ingresos, gastos y resultados netos registrados para cada mes.", unavailable: "Reporte no disponible", income: "Ingresos", expenses: "Gastos", net: "Resultado neto", month: "Mes", year: "Año", viewReport: "Ver reporte", total: "Total del año", details: "Detalles por categoría", back: "Volver al reporte mensual", transactions: "transacciones", empty: "No hay transacciones registradas para esta selección.", date: "Fecha", description: "Descripción", fund: "Fondo", account: "Cuenta", reference: "Referencia de pago", amount: "Monto", downloadPdf: "Descargar PDF", detailedDownload: "Reporte PDF detallado", detailedDownloadText: "Descargue cada transacción correspondiente al año completo o a un mes.", period: "Período", fullYear: "Año completo", transactionType: "Tipo de transacción", allTransactions: "Todas las transacciones", downloadDetailedPdf: "Descargar PDF detallado" },
    settings: { title: "Usuarios y permisos", lede: "Vea los miembros de la organización y controle lo que cada persona puede hacer.", organization: "Organización", members: "Miembros", member: "Miembro", role: "Rol", joined: "Se unió", currentUser: "Usted", save: "Guardar rol", saving: "Guardando…", saved: "Rol actualizado.", administratorOnly: "Solo los administradores pueden cambiar los roles.", finalAdministrator: "Agregue otro administrador antes de cambiar este rol.", inviteTitle: "Invitar una cuenta nueva", inviteText: "Envíe una invitación por correo para que la persona cree su contraseña y se una a la organización.", invite: "Enviar invitación", inviting: "Enviando…", invited: "Invitación enviada y miembro agregado.", inviteError: "No se pudo completar la invitación. Confirme que el correo no esté registrado y que las invitaciones estén configuradas.", setupLink: "Enviar enlace de configuración", sendingSetupLink: "Enviando…", setupLinkSent: "Enlace de configuración enviado.", setupLinkError: "No se pudo enviar el enlace de configuración.", activeStatus: "Acceso activo", inactiveStatus: "Acceso desactivado", deactivate: "Desactivar acceso", deactivating: "Desactivando…", deactivateConfirm: "¿Desactivar el acceso de este miembro? Perderá inmediatamente el acceso a los datos financieros de la iglesia, pero se conservará su historial de auditoría.", deactivated: "Acceso del miembro desactivado.", restore: "Restaurar acceso", restoring: "Restaurando…", restored: "Acceso del miembro restaurado.", accessError: "No se pudo cambiar el acceso del miembro.", addTitle: "Agregar una cuenta existente", addText: "Use esta opción cuando la persona ya tenga una cuenta en Autenticación de Supabase.", email: "Correo de la cuenta", addRole: "Rol inicial", add: "Agregar miembro", adding: "Agregando…", added: "Miembro agregado.", addError: "No se pudo agregar el miembro. Confirme que la cuenta existe y no está asignada.", unavailable: "Miembros no disponibles", errors: "No se pudo cambiar el rol.", roleLabels: { administrator: "Administrador", treasurer: "Tesorero", data_entry: "Entrada de datos", approver: "Aprobador", viewer: "Solo lectura" } },
    invitation: { title: "Cree su contraseña", lede: "Termine de configurar su cuenta de finanzas de la iglesia.", password: "Contraseña", confirmPassword: "Confirmar contraseña", save: "Crear cuenta", saving: "Creando cuenta…", mismatch: "Las contraseñas no coinciden.", invalid: "Esta invitación no es válida o ha vencido. Pida una nueva invitación al administrador.", success: "Cuenta creada." },
    accounts: { title: "Cuentas financieras", lede: "Controle los saldos de cheques, ahorros, efectivo y caja chica en un solo lugar.", unavailable: "Cuentas no disponibles", createTitle: "Crear cuenta financiera", createText: "Agregue una cuenta y su saldo inicial. Solo los administradores pueden crear cuentas.", name: "Nombre de la cuenta", type: "Tipo de cuenta", openingBalance: "Saldo inicial", openingBalanceHint: "El saldo antes de las transacciones registradas en esta aplicación.", create: "Crear cuenta", creating: "Creando…", created: "Cuenta financiera creada.", createError: "No se pudo crear la cuenta financiera.", administratorOnly: "Solo los administradores pueden crear cuentas financieras.", currentBalance: "Saldo actual", opening: "Saldo inicial", noAccounts: "No se han creado cuentas financieras.", status: "Estado", active: "Activa", inactive: "Inactiva", manage: "Administrar cuenta", saveChanges: "Guardar cambios", savingChanges: "Guardando…", updated: "Cuenta financiera actualizada.", updateError: "No se pudo actualizar la cuenta financiera.", finalActive: "No se puede desactivar la última cuenta activa.", typeLabels: { checking: "Cheques", savings: "Ahorros", cash: "Efectivo", petty_cash: "Caja chica", other: "Otra" } },
    categoryManagement: { title: "Administración de categorías", lede: "Administre las categorías de ingresos y gastos disponibles al registrar transacciones.", createTitle: "Crear categoría", createText: "Elija si la categoría nueva es para dinero recibido o dinero pagado.", name: "Nombre de la categoría", type: "Tipo de categoría", income: "Ingreso", expense: "Gasto", create: "Crear categoría", creating: "Creando…", created: "Categoría creada.", createError: "No se pudo crear la categoría.", administratorOnly: "Solo los administradores pueden administrar categorías.", status: "Estado", active: "Activa", inactive: "Inactiva", manage: "Administrar categoría", saveChanges: "Guardar cambios", savingChanges: "Guardando…", updated: "Categoría actualizada.", updateError: "No se pudo actualizar la categoría.", noCategories: "No se han creado categorías." },
    fundManagement: { title: "Administración de fondos", lede: "Administre los fondos designados disponibles al registrar transacciones.", createTitle: "Crear fondo", createText: "Agregue un propósito o designación para controlar ingresos y gastos.", name: "Nombre del fondo", create: "Crear fondo", creating: "Creando…", created: "Fondo creado.", createError: "No se pudo crear el fondo.", administratorOnly: "Solo los administradores pueden administrar fondos.", status: "Estado", active: "Activo", inactive: "Inactivo", manage: "Administrar fondo", saveChanges: "Guardar cambios", savingChanges: "Guardando…", updated: "Fondo actualizado.", updateError: "No se pudo actualizar el fondo.", noFunds: "No se han creado fondos." },
    budgetManagement: { title: "Administración de presupuestos", lede: "Establezca metas mensuales de gastos y compárelas con los gastos registrados.", createTitle: "Establecer presupuesto mensual", createText: "Guardar la misma categoría y mes actualiza el presupuesto existente.", category: "Categoría de gasto", month: "Mes del presupuesto", amount: "Monto del presupuesto", save: "Guardar presupuesto", saving: "Guardando…", saved: "Presupuesto guardado.", error: "No se pudo guardar el presupuesto.", administratorOnly: "Solo los administradores pueden administrar presupuestos.", noBudgets: "No se han establecido presupuestos para este año.", budgeted: "Presupuestado", actual: "Gasto real", remaining: "Restante", over: "Sobre el presupuesto", viewYear: "Ver año" },
    pages: { accounts: "Cuentas", financialAccounts: "Cuentas financieras", accountsLater: "Las cuentas de cheques, ahorros y efectivo se implementarán más adelante.", reports: "Reportes", financialReports: "Reportes financieros", reportsLater: "Los reportes se agregarán después de aprobar el registro de transacciones.", administration: "Administración", settings: "Configuración", settingsLater: "Las categorías, fondos, usuarios y permisos se implementarán más adelante.", transactions: "Transacciones", register: "Registro de transacciones", registerText: "El registro de ingresos y gastos está disponible." },
    expense: { eyebrow: "Transacciones", title: "Registrar gasto", lede: "Ingrese los datos del pago. El servidor valida y guarda el gasto en el registro contable de la iglesia.", amount: "Monto", date: "Fecha de la transacción", category: "Categoría de gasto", categoryHint: "Las categorías de gasto representan dinero pagado y disminuyen el saldo disponible.", selectCategory: "Seleccione una categoría de gasto", fund: "Fondo o propósito", selectFund: "Seleccione un fondo", description: "Descripción", reference: "Referencia de cheque o tarjeta (opcional)", save: "Guardar gasto", saving: "Guardando…", saved: "Gasto guardado", transactionReference: "Referencia de transacción", paymentReference: "Referencia de pago", none: "Ninguna", invalid: "No se pudo validar el gasto." },
    categories: ["Building rent", "Utilities", "Bank fees", "Church insurance", "Essential supplies", "Pastor support and travel", "Children's guides", "Magazine and literature", "Presbytery contributions", "Other expense"],
    categoryLabels: ["Pago de renta del edificio (dinero pagado)", "Servicios públicos", "Cargos bancarios", "Seguro de la iglesia", "Artículos de primera necesidad", "Apoyo al pastor y viajes", "Guías infantiles", "Revistas y literatura", "Aportaciones presbiteriales", "Otro gasto"],
    funds: ["Support of the work", "General congregation", "Children's commission", "Legal and building", "Presbytery"],
    fundLabels: ["Sustento de la obra", "Congregación general", "Comisión infantil", "Legal y edificio", "Presbiterio"],
  },
} as const;
export function getMessages(locale: Locale) { return messages[locale]; }

const spanishCategoryLabels: Record<string, string> = {
  "Tithe": "Diezmo", "Church offering": "Ofrenda de la iglesia", "Children's offering": "Ofrenda infantil", "First fruits": "Primicias", "Talent / food": "Talento / alimentos", "Temple rent": "Ingreso por renta del templo", "General support": "Apoyo general",
  "Building rent": "Pago de renta del edificio", "Utilities": "Servicios públicos", "Bank fees": "Cargos bancarios", "Church insurance": "Seguro de la iglesia", "Essential supplies": "Artículos de primera necesidad", "Pastor support and travel": "Apoyo al pastor y viajes", "Children's guides": "Guías infantiles", "Magazine and literature": "Revistas y literatura", "Presbytery contributions": "Aportaciones presbiteriales", "Other expense": "Otro gasto",
};
export function getCategoryLabel(locale: Locale, category: string) { return locale === "es" ? (spanishCategoryLabels[category] ?? category) : category; }
const spanishFundLabels: Record<string, string> = { "Support of the work": "Sustento de la obra", "General congregation": "Congregación general", "Children's commission": "Comisión infantil", "Legal and building": "Legal y edificio", "Presbytery": "Presbiterio" };
export function getFundLabel(locale: Locale, fund: string) { return locale === "es" ? (spanishFundLabels[fund] ?? fund) : fund; }
export function getAccountLabel(locale: Locale, account: string) { return locale === "es" && account === "Checking" ? "Cuenta de cheques" : account; }
