export type Locale = "en" | "es";

export const messages = {
  en: {
    language: "Español", brand: "Church Finance",
    nav: { dashboard: "Dashboard", activity: "Activity", transaction: "Record transaction", income: "Record income", expense: "Record expense", reports: "Reports", primary: "Primary navigation" },
    account: { signedIn: "Signed in as", signOut: "Sign out", signingOut: "Signing out…" },
    login: { title: "Sign in", lede: "Use your authorized church account to continue.", loading: "Loading sign-in…", email: "Email address", password: "Password", signIn: "Sign in", signingIn: "Signing in…", error: "The email or password is incorrect." },
    dashboard: { title: "Financial overview", lede: "Posted activity across the organization’s financial accounts.", unavailable: "Summary unavailable", balance: "Available balance", income: "Income this month", expenses: "Expenses this month", summary: "Financial summary", activity: "View activity" },
    transaction: { eyebrow: "Transactions", title: "Record transaction", lede: "Choose whether money was received or paid, then select the matching category and details.", type: "Transaction type", typeHint: "Income increases the balance. Expenses decrease the balance.", income: "Income — money received", expense: "Expense — money paid", contributions: "Contributions and offerings", earnedIncome: "Rental and earned income", facilities: "Facilities", operations: "Operations", ministry: "Ministry and church support", other: "Other" },
    income: { eyebrow: "Transactions", title: "Record income", lede: "Enter the deposit details below. The server validates and saves the transaction to the church ledger.", amount: "Amount", date: "Transaction date", category: "Income category", categoryHint: "Income categories represent money received and increase the available balance.", selectCategory: "Select an income category", fund: "Fund or purpose", selectFund: "Select a fund", description: "Description", save: "Save income", saving: "Saving…", saved: "Income saved", reference: "Reference", invalid: "The transaction could not be validated." },
    activity: { eyebrow: "Activity", title: "Transaction activity", lede: "The latest posted income and expenses for your organization.", unavailable: "Activity unavailable", empty: "No transactions yet", emptyText: "Saved income and expense transactions will appear here.", date: "Date", type: "Type", incomeType: "Income", expenseType: "Expense", description: "Description", category: "Category", fund: "Fund", account: "Account", amount: "Amount", ref: "Ref.", paymentRef: "Payment" },
    reports: { eyebrow: "Reports", title: "Monthly financial report", lede: "Posted income, expenses, and net results for each month.", unavailable: "Report unavailable", income: "Income", expenses: "Expenses", net: "Net result", month: "Month", year: "Year", viewReport: "View report", total: "Year total", details: "Category details", back: "Back to monthly report", transactions: "transactions", empty: "No posted transactions for this selection.", date: "Date", description: "Description", fund: "Fund", account: "Account", reference: "Payment reference", amount: "Amount", downloadPdf: "Download PDF", detailedDownload: "Detailed PDF report", detailedDownloadText: "Download every matching transaction for the full year or one month.", period: "Period", fullYear: "Full year", transactionType: "Transaction type", allTransactions: "All transactions", downloadDetailedPdf: "Download detailed PDF" },
    pages: { accounts: "Accounts", financialAccounts: "Financial accounts", accountsLater: "Checking, savings, and cash accounts will be implemented later.", reports: "Reports", financialReports: "Financial reports", reportsLater: "Reports will be added after transaction persistence is approved.", administration: "Administration", settings: "Settings", settingsLater: "Categories, funds, users, and permissions will be implemented later.", transactions: "Transactions", register: "Transaction register", registerText: "Income and expense entry are available." },
    expense: { eyebrow: "Transactions", title: "Record expense", lede: "Enter the payment details below. The server validates and saves the expense to the church ledger.", amount: "Amount", date: "Transaction date", category: "Expense category", categoryHint: "Expense categories represent money paid and decrease the available balance.", selectCategory: "Select an expense category", fund: "Fund or purpose", selectFund: "Select a fund", description: "Description", reference: "Check or card reference (optional)", save: "Save expense", saving: "Saving…", saved: "Expense saved", transactionReference: "Transaction reference", paymentReference: "Payment reference", none: "None", invalid: "The expense could not be validated." },
    categories: ["Building rent", "Utilities", "Bank fees", "Church insurance", "Essential supplies", "Pastor support and travel", "Children's guides", "Magazine and literature", "Presbytery contributions", "Other expense"],
    categoryLabels: ["Building rent payment (money paid)", "Utilities", "Bank fees", "Church insurance", "Essential supplies", "Pastor support and travel", "Children’s guides", "Magazine and literature", "Presbytery contributions", "Other expense"],
    funds: ["Support of the work", "General congregation", "Children's commission", "Legal and building", "Presbytery"],
    fundLabels: ["Support of the work", "General congregation", "Children’s commission", "Legal and building", "Presbytery"],
  },
  es: {
    language: "English", brand: "Finanzas de la Iglesia",
    nav: { dashboard: "Resumen", activity: "Actividad", transaction: "Registrar transacción", income: "Registrar ingreso", expense: "Registrar gasto", reports: "Reportes", primary: "Navegación principal" },
    account: { signedIn: "Sesión iniciada como", signOut: "Cerrar sesión", signingOut: "Cerrando sesión…" },
    login: { title: "Iniciar sesión", lede: "Use su cuenta autorizada de la iglesia para continuar.", loading: "Cargando inicio de sesión…", email: "Correo electrónico", password: "Contraseña", signIn: "Iniciar sesión", signingIn: "Iniciando sesión…", error: "El correo electrónico o la contraseña son incorrectos." },
    dashboard: { title: "Resumen financiero", lede: "Actividad registrada en las cuentas financieras de la organización.", unavailable: "Resumen no disponible", balance: "Saldo disponible", income: "Ingresos de este mes", expenses: "Gastos de este mes", summary: "Resumen financiero", activity: "Ver actividad" },
    transaction: { eyebrow: "Transacciones", title: "Registrar transacción", lede: "Elija si el dinero fue recibido o pagado y después seleccione la categoría y los detalles correspondientes.", type: "Tipo de transacción", typeHint: "Los ingresos aumentan el saldo. Los gastos disminuyen el saldo.", income: "Ingreso — dinero recibido", expense: "Gasto — dinero pagado", contributions: "Aportaciones y ofrendas", earnedIncome: "Rentas e ingresos obtenidos", facilities: "Edificio e instalaciones", operations: "Operaciones", ministry: "Ministerio y apoyo de la iglesia", other: "Otros" },
    income: { eyebrow: "Transacciones", title: "Registrar ingreso", lede: "Ingrese los datos del depósito. El servidor valida y guarda la transacción en el registro contable de la iglesia.", amount: "Monto", date: "Fecha de la transacción", category: "Categoría de ingreso", categoryHint: "Las categorías de ingreso representan dinero recibido y aumentan el saldo disponible.", selectCategory: "Seleccione una categoría de ingreso", fund: "Fondo o propósito", selectFund: "Seleccione un fondo", description: "Descripción", save: "Guardar ingreso", saving: "Guardando…", saved: "Ingreso guardado", reference: "Referencia", invalid: "No se pudo validar la transacción." },
    activity: { eyebrow: "Actividad", title: "Actividad de transacciones", lede: "Los ingresos y gastos registrados más recientes de su organización.", unavailable: "Actividad no disponible", empty: "Aún no hay transacciones", emptyText: "Los ingresos y gastos guardados aparecerán aquí.", date: "Fecha", type: "Tipo", incomeType: "Ingreso", expenseType: "Gasto", description: "Descripción", category: "Categoría", fund: "Fondo", account: "Cuenta", amount: "Monto", ref: "Ref.", paymentRef: "Pago" },
    reports: { eyebrow: "Reportes", title: "Reporte financiero mensual", lede: "Ingresos, gastos y resultados netos registrados para cada mes.", unavailable: "Reporte no disponible", income: "Ingresos", expenses: "Gastos", net: "Resultado neto", month: "Mes", year: "Año", viewReport: "Ver reporte", total: "Total del año", details: "Detalles por categoría", back: "Volver al reporte mensual", transactions: "transacciones", empty: "No hay transacciones registradas para esta selección.", date: "Fecha", description: "Descripción", fund: "Fondo", account: "Cuenta", reference: "Referencia de pago", amount: "Monto", downloadPdf: "Descargar PDF", detailedDownload: "Reporte PDF detallado", detailedDownloadText: "Descargue cada transacción correspondiente al año completo o a un mes.", period: "Período", fullYear: "Año completo", transactionType: "Tipo de transacción", allTransactions: "Todas las transacciones", downloadDetailedPdf: "Descargar PDF detallado" },
    pages: { accounts: "Cuentas", financialAccounts: "Cuentas financieras", accountsLater: "Las cuentas de cheques, ahorros y efectivo se implementarán más adelante.", reports: "Reportes", financialReports: "Reportes financieros", reportsLater: "Los reportes se agregarán después de aprobar el registro de transacciones.", administration: "Administración", settings: "Configuración", settingsLater: "Las categorías, fondos, usuarios y permisos se implementarán más adelante.", transactions: "Transacciones", register: "Registro de transacciones", registerText: "El registro de ingresos y gastos está disponible." },
    expense: { eyebrow: "Transacciones", title: "Registrar gasto", lede: "Ingrese los datos del pago. El servidor valida y guarda el gasto en el registro contable de la iglesia.", amount: "Monto", date: "Fecha de la transacción", category: "Categoría de gasto", categoryHint: "Las categorías de gasto representan dinero pagado y disminuyen el saldo disponible.", selectCategory: "Seleccione una categoría de gasto", fund: "Fondo o propósito", selectFund: "Seleccione un fondo", description: "Descripción", reference: "Referencia de cheque o tarjeta (opcional)", save: "Guardar gasto", saving: "Guardando…", saved: "Gasto guardado", transactionReference: "Referencia de transacción", paymentReference: "Referencia de pago", none: "Ninguna", invalid: "No se pudo validar el gasto." },
    categories: ["Building rent", "Utilities", "Bank fees", "Church insurance", "Essential supplies", "Pastor support and travel", "Children's guides", "Magazine and literature", "Presbytery contributions", "Other expense"],
    categoryLabels: ["Pago de renta del edificio (dinero pagado)", "Servicios públicos", "Cargos bancarios", "Seguro de la iglesia", "Artículos de primera necesidad", "Apoyo al pastor y viajes", "Guías infantiles", "Revistas y literatura", "Aportaciones presbiteriales", "Otro gasto"],
    funds: ["Support of the work", "General congregation", "Children's commission", "Legal and building", "Presbytery"],
    fundLabels: ["Sustento de la obra", "Congregación general", "Comisión infantil", "Legal y edificio", "Presbiterio"],
  },
} as const;
export function getMessages(locale: Locale) { return messages[locale]; }

const spanishCategoryLabels: Record<string, string> = {
  "Tithe": "Diezmo", "Church offering": "Ofrenda de la iglesia", "Children's offering": "Ofrenda infantil", "First fruits": "Primicias", "Talent / food": "Talento / alimentos", "Temple rent": "Ingreso por renta del templo", "General support": "Apoyo general",
  "Building rent": "Pago de renta del edificio", "Utilities": "Servicios públicos", "Bank fees": "Cargos bancarios", "Church insurance": "Seguro de la iglesia", "Essential supplies": "Artículos de primera necesidad", "Pastor support and travel": "Apoyo al pastor y viajes", "Children's guides": "Guías infantiles", "Magazine and literature": "Revistas y literatura", "Presbytery contributions": "Aportaciones presbiteriales", "Other expense": "Otro gasto",
};
export function getCategoryLabel(locale: Locale, category: string) { return locale === "es" ? (spanishCategoryLabels[category] ?? category) : category; }
const spanishFundLabels: Record<string, string> = { "Support of the work": "Sustento de la obra", "General congregation": "Congregación general", "Children's commission": "Comisión infantil", "Legal and building": "Legal y edificio", "Presbytery": "Presbiterio" };
export function getFundLabel(locale: Locale, fund: string) { return locale === "es" ? (spanishFundLabels[fund] ?? fund) : fund; }
export function getAccountLabel(locale: Locale, account: string) { return locale === "es" && account === "Checking" ? "Cuenta de cheques" : account; }
